export const DB_NAME = 'KaushalSetuAI';

export const DOMAINS = {
    tech: [
        'software',
        'developer',
        'engineer',
        'programming',
        'it',
        'data',
        'cloud',
        'devops',
        'ai',
        'ml',
        'web',
        'mobile',
        'fullstack',
        'frontend',
        'backend',
        'fullstack-developer',
        'qa',
        'sre',
        'platform',
        'infrastructure',
        'security',
        'cybersecurity',
        'blockchain',
        'embedded',
        'firmware',
        'architect',
    ],
    medical: [
        'doctor',
        'nurse',
        'hospital',
        'clinical',
        'pharma',
        'medical',
        'healthcare',
        'physician',
        'surgeon',
        'dentist',
        'therapist',
        'radiologist',
        'pathologist',
    ],
    law: [
        'lawyer',
        'advocate',
        'legal',
        'law',
        'paralegal',
        'counsel',
        'attorney',
        'solicitor',
        'barrister',
        'compliance officer',
    ],
    finance: [
        'finance',
        'accounting',
        'bank',
        'auditor',
        'investment',
        'actuary',
        'trader',
        'analyst',
        'risk',
        'treasury',
        'fintech',
        'hedge fund',
    ],
    education: [
        'teacher',
        'professor',
        'education',
        'school',
        'lecturer',
        'tutor',
        'instructor',
        'curriculum',
        'academic',
        'e-learning',
    ],
    design: [
        'design',
        'ui',
        'ux',
        'graphic',
        'designer',
        'visual',
        'illustrator',
        'motion',
        'brand',
        'typography',
        'interaction design',
    ],
    management: [
        'manager',
        'management',
        'project',
        'product',
        'scrum',
        'agile',
        'director',
        'head of',
        'vp of',
        'chief',
        'operations',
        'strategy',
        'program manager',
        'delivery manager',
    ],
    government: [
        'government',
        'public sector',
        'civil service',
        'federal',
        'state agency',
        'municipal',
        'policy',
        'regulatory',
    ],
};

export const EXPERIENCE_SIGNALS = {
    advanced: [
        /\bsenior\b/,
        /\bsr\.\b/,
        /\blead\b/,
        /\bprincipal\b/,
        /\bstaff\b/,
        /\barchitect\b/,
        /\bdirector\b/,
        /\bhead of\b/,
        /\bvp\b/,
        /\bc[teo]o\b/,
        /\b8\+?\s*years?\b/,
        /\b7\+?\s*years?\b/,
        /\b6\+?\s*years?\b/,
        /\bexpert\b/,
        /\bspecialist\b/,
    ],
    intermediate: [
        /\bmid[\s-]?level\b/,
        /\bexperienced\b/,
        /\b3\+?\s*years?\b/,
        /\b4\+?\s*years?\b/,
        /\b5\+?\s*years?\b/,
        /\bjunior[\s-]?senior\b/,
    ],
    beginner: [
        /\bjunior\b/,
        /\bjr\.\b/,
        /\bentry[\s-]?level\b/,
        /\bfresher\b/,
        /\bintern\b/,
        /\bgraduate\b/,
        /\btrainee\b/,
        /\bapprentice\b/,
        /\bno experience\b/,
        /\b0[\s-]?1\s*years?\b/,
        /\b1\+?\s*year\b/,
    ],
};

export const SALARY_BENCHMARKS = {
    tech: {
        beginner: { min: 400000, max: 800000 },
        intermediate: { min: 900000, max: 1800000 },
        advanced: { min: 2000000, max: 5000000 },
    },
    medical: {
        beginner: { min: 350000, max: 700000 },
        intermediate: { min: 700000, max: 1500000 },
        advanced: { min: 1500000, max: 4000000 },
    },
    law: {
        beginner: { min: 300000, max: 600000 },
        intermediate: { min: 700000, max: 1400000 },
        advanced: { min: 1500000, max: 4000000 },
    },
    finance: {
        beginner: { min: 400000, max: 800000 },
        intermediate: { min: 900000, max: 1800000 },
        advanced: { min: 2000000, max: 5000000 },
    },
    education: {
        beginner: { min: 250000, max: 500000 },
        intermediate: { min: 500000, max: 1000000 },
        advanced: { min: 1000000, max: 2500000 },
    },
    design: {
        beginner: { min: 350000, max: 700000 },
        intermediate: { min: 800000, max: 1500000 },
        advanced: { min: 1600000, max: 3500000 },
    },
    management: {
        beginner: { min: 500000, max: 1000000 },
        intermediate: { min: 1200000, max: 2500000 },
        advanced: { min: 2500000, max: 6000000 },
    },
    government: {
        beginner: { min: 250000, max: 500000 },
        intermediate: { min: 500000, max: 1000000 },
        advanced: { min: 1000000, max: 2000000 },
    },
    other: {
        beginner: { min: 300000, max: 600000 },
        intermediate: { min: 600000, max: 1200000 },
        advanced: { min: 1200000, max: 3000000 },
    },
};

export const DOMAIN_SKILLS = {
    tech: [
        'javascript',
        'typescript',
        'react',
        'node',
        'python',
        'aws',
        'docker',
        'kubernetes',
        'sql',
        'mongodb',
        'git',
    ],
    medical: [
        'patient care',
        'clinical research',
        'nursing',
        'pharmacology',
        'diagnosis',
        'medical coding',
        'ehr',
    ],
    law: [
        'legal research',
        'drafting',
        'litigation',
        'contract law',
        'compliance',
        'due diligence',
    ],
    finance: [
        'accounting',
        'auditing',
        'financial analysis',
        'taxation',
        'investment banking',
        'excel',
        'bloomberg',
    ],
    education: [
        'curriculum development',
        'lesson planning',
        'classroom management',
        'assessment',
        'e-learning',
    ],
    design: [
        'figma',
        'adobe xd',
        'ui design',
        'ux research',
        'wireframing',
        'prototyping',
        'illustrator',
    ],
    management: [
        'project management',
        'agile',
        'scrum',
        'stakeholder management',
        'roadmapping',
        'jira',
        'confluence',
    ],
    government: [
        'policy analysis',
        'public administration',
        'regulatory compliance',
        'report writing',
    ],
};

export const DOMAIN_KEYWORDS = {
    tech: [
        'software developer',
        'frontend developer',
        'backend developer',
        'full stack developer',
        'data engineer',
        'machine learning engineer',
        'devops engineer',
        'cloud engineer',
        'security engineer',
    ],
    medical: ['doctor', 'nurse', 'medical officer', 'clinical research', 'pharmacist'],
    law: ['lawyer', 'legal associate', 'advocate', 'paralegal'],
    finance: ['accountant', 'finance analyst', 'banking officer', 'investment analyst'],
    education: ['teacher', 'lecturer', 'professor', 'education coordinator'],
    design: ['ui designer', 'ux designer', 'graphic designer', 'product designer'],
    management: ['product manager', 'project manager', 'operations manager'],
};

export const SKILL_PATTERNS = [
    /\b(javascript|typescript|python|java|c\+\+|c#|go|golang|rust|ruby|php|swift|kotlin|scala|r\b)\b/gi,
    /\b(react(\.js)?|next(\.js)?|vue(\.js)?|angular|svelte|node(\.js)?|express(\.js)?|nestjs|django|flask|fastapi|spring|laravel|rails)\b/gi,
    /\b(postgresql|postgres|mysql|mongodb|redis|elasticsearch|cassandra|dynamodb|sqlite|oracle|mssql)\b/gi,
    /\b(aws|azure|gcp|google cloud|terraform|kubernetes|k8s|docker|helm|ansible|jenkins|github actions|ci\/cd)\b/gi,
    /\b(tensorflow|pytorch|scikit-learn|pandas|numpy|spark|hadoop|kafka|airflow|dbt|mlflow)\b/gi,
    /\b(git|linux|rest(ful)?( api)?|graphql|grpc|microservices|agile|scrum|jira|figma|sql)\b/gi,
];
